// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rapxmkkctesaotksvnfb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhcHhta2tjdGVzYW90a3N2bmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTkyNjAsImV4cCI6MjA2OTEzNTI2MH0.9BFmNfuA3zjAe-ZD1iCgk7V0CkZ9Wi_wtsjKU8n2hxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});